name: moviesapp
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^1.0.3
  glassmorphism: ^3.0.0
  flutter_rating_bar: ^4.0.0
  google_fonts: 2.2.0
  device_preview: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/mask/
    - assets/movie-posters/
    - assets/svg/